In [ ]:
import numpy as np
arr=np.array([10,20,21,12321,32])
print("First element:",arr[0])

First element: 10


In [ ]:
import numpy as np
arr=np.array([[10,20,21,12321,32],
             [10,20,21,12321,32]])
print("First row, second column:",arr[0:1])

First row, second column: [[   10    20    21 12321    32]]


In [ ]:
import numpy as np
arr=np.array([[10,20,21,12321,32],
              [10,20,21,12321,3],
              [10,20,21,12321,3]])
Ar=arr[ 0:2 , 2:4]
print(Ar)

[[   21 12321]
 [   21 12321]]


In [ ]:
import numpy as np
A=np.array([1,2,3])
print(A+10)
print(A*2)
print(np.sqrt(A))

[11 12 13]
[2 4 6]
[1.         1.41421356 1.73205081]


In [ ]:
import numpy as np
A=np.array([[1,2,3],
           [4,5,6]])
print(np.sum(A,axis=1))
print(np.sum(A,axis=0))
print(np.mean(A))
print(A.T)


[ 6 15]
[5 7 9]
3.5
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
A=np.arange(24).reshape(2,3,4)
print(A.shape)
print(A[1][2][3])

(2, 3, 4)
23


In [ ]:
import numpy as np
a= np.arange(12)
print (a)
# reshape
print("\n reshaped array(4*3):")
print(a.reshape(4,3))
#flatten
print("\n flatten array:")
print(a.reshape(4,3).flatten())
#change data type
print("\n array after astype(float):")
print(a.astype(float))
#transpose
print("\n transpose of 4*3 array:")
print(a.reshape(4,3).T)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array(4*3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 flatten array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

 array after astype(float):
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

 transpose of 4*3 array:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [8]:
import numpy as np
G = np.array(([1,2],[3,4]))
T = np.array(([5,6],[7,8]))
print(G)
print(T)
print(np.concatenate((G,T),axis = 0))
print(np.concatenate((G,T),axis = 1))
print(np.hstack((G,T)))
print(np.vstack((G,T)))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
import numpy as np
v1=np.array([1,2])
v2=np.array([3,4])
print(np.dot(v1,v2))
A=np.array([[1,2],
            [3,4]])
B=np.array([[5,6],
            [7,8]])
print(A@B)
print(A.dot(B))
print(np.linalg.det(A))
print(np.linalg.inv(A))

11
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
