In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

[10 20 30 40 50]
10
20
30
40
50


In [ ]:
import pandas as pd
data={
    "name":["Rohith","Laxmi","Vishnu"],
    "Age":[10,9,8],
    "Branch":["AIML","CS","AIML"]
}
df= pd.DataFrame(data)
print(df)

In [ ]:
import numpy as np
a=np.array([[1,2],
       [3,4]])
b=np.array([[5,6],
      [7,8]])
c=np.concatenate((a,b),axis=0)
d=np.concatenate((a,b),axis=1)
h=np.hstack((a,b))
v=np.vstack((a,b))
print(c)
print(d)
print(h)
print(v)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["A","B","c"],
    "Age":[18,19,20],
    "Marks":[70,80,90]
})
print(df.loc[1,"Marks"])
print(df.iloc[0,1])

80
18


In [2]:
import pandas as pd
data={
    "region":["North","South","North","East","South","East","North"],
    "sales":[200,150,300,250,180,220,275]
}
df=pd.DataFrame(data)
print(df)
region_sales=df.groupby("region")["sales"].sum()
print(region_sales)

data={
    "machine":["M1","M1","M2","M2","M3"],
    "defects":[12,15,8,10,25,]
}
df=pd.DataFrame(data)
print(df)
result=df.groupby("machine")["defects"].sum()
print(result)

data={
    "transaction":["T1","T2","T3","T4","T5"],
    "amount":[5000,7000,6500,6000,7200]
}
df=pd.DataFrame(data)
print(df)
Q1=df["amount"].quantile(0.25)
Q3=df["amount"].quantile(0.75)
IQR=Q3-Q1
lowerbound=Q1-1.5*IQR
upperbound=Q3+1.5*IQR
print(lowerbound)
print(upperbound)
outliers=df[(df["amount"]<lowerbound)|(df["amount"]>upperbound)]
print(outliers)

  region  sales
0  North    200
1  South    150
2  North    300
3   East    250
4  South    180
5   East    220
6  North    275
region
East     470
North    775
South    330
Name: sales, dtype: int64
  machine  defects
0      M1       12
1      M1       15
2      M2        8
3      M2       10
4      M3       25
machine
M1    27
M2    18
M3    25
Name: defects, dtype: int64
  transaction  amount
0          T1    5000
1          T2    7000
2          T3    6500
3          T4    6000
4          T5    7200
4500.0
8500.0
Empty DataFrame
Columns: [transaction, amount]
Index: []
